name: Release Go Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Build binaries
        run: |
          mkdir -p dist
          mkdir -p binary

          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o binary/linux/nav
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o binary/darwin/nav
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o binary/windows/nav.exe
          chmod +x binary/darwin/* binary/linux/*

          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/nav-linux-amd64 installer/main.go
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/nav-darin-amd64 installer/main.go
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/nav-windows-amd64.exe installer/main.go
          chmod +x dist/nav-linux* dist/nav-darwin**

          rm -rf binary/
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERMISSIONS: write
